name: Quality Checks

on:
    push:
        branches:
            - '**'
        pull_request:
            - '**'

env:
  DENO_VERSION: 1.37.2

jobs:
    quality-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Deno Version ${{ env.DENO_VERSION }}
              uses: denolib/setup-deno@v2
              with:
                deno-version: ${{ env.DENO_VERSION }}
            - name: Typecheck
              run: deno check src/main.ts
            - name: Format Check
              run: deno fmt --check
            - name: Lint
              run: deno lint
            - name: Test
              run: deno test
