name: Quality Checks

on:
    push:
        branches:
            - '**'
        pull_request:
            - '**'
    workflow_call:

env:
    NODE_VERSION: 20

jobs:
    quality-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node Version ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Install Dependencies
              run: yarn install --immutable
            - name: Typecheck
              run: yarn typecheck
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
